kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 8443 ssl;
      server_name localhost;

      ssl_certificate /etc/nginx/tls/nginx.crt;
      ssl_certificate_key /etc/nginx/tls/nginx.key;

      location / {
        proxy_pass <flink-rest-ui-url>;
        auth_basic "Flink-UI";
        auth_basic_user_file /etc/nginx/.htpasswd;
      }
    }